name:                alpha
version:             0.0.128
github:              "0xCM/alpha"
license:             MIT
author:              "Chris Moore"
maintainer:          "0xCM00@gmail.com"
copyright:           "2018 Chris Moore"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/githubuser/alpha#readme>

default-extensions:
  AllowAmbiguousTypes
  BinaryLiterals
  BlockArguments
  ConstraintKinds
  DefaultSignatures
  DeriveDataTypeable
  DeriveFoldable
  DeriveGeneric
  DeriveTraversable
  DuplicateRecordFields
  FunctionalDependencies
  FlexibleInstances
  FlexibleContexts
  GADTs
  GeneralizedNewtypeDeriving
  HexFloatLiterals
  ImplicitParams
  InstanceSigs
  KindSignatures
  LambdaCase
  LiberalTypeSynonyms
  MonadComprehensions
  MultiParamTypeClasses
  MultiWayIf
  NoImplicitPrelude
  OverloadedLabels
  OverloadedStrings
  ParallelListComp
  PatternSynonyms
  PolyKinds
  PostfixOperators
  QuasiQuotes
  RankNTypes
  RecursiveDo
  RoleAnnotations
  ScopedTypeVariables
  StandaloneDeriving
  TransformListComp
  TupleSections
  TypeApplications
  TypeInType
  TypeFamilies
  TypeFamilyDependencies
  TypeOperators
  TypeSynonymInstances
  ViewPatterns
  UnicodeSyntax
  

dependencies:
- array
- base
- binary
- bytestring
- containers
- deepseq
- directory
- filepath
- ghc
- ghc-prim
- ghc-paths
- mtl
- parallel
- parsec
- process
- stm
- text
- template-haskell
- transformers
- time

- adjunctions
- aeson
- aeson-pretty
- ansi-terminal
- bifunctors
- comonad
- contravariant
- data-default
- distributive
- either
- entropy
- hashable
- intervals
- keys
- lattices
- matrix
- multiset
- network
- primitive
- profunctors
- range
- semigroupoids
- semigroups
- streams
- tagged
- unordered-containers
- vector

# - adjunctions
# - async
# - attoparsec
# - base-orphans
# - bytestring-builder
# - cmdargs
# - contravariant
# - dlist
# - fail
# - generic-deriving
# - haskell-src-exts
# - integer-gmp
# - integer-logarithms
# - mwc-random
# - nats
# - typed-process
# - pipes
# - prettyclass
# - profunctors
# - scientific
# - statistics

# - th-abstraction
# - time-locale-compat
# - uuid-types
# - void


library:
  source-dirs: src

executables:
  alpha-test:
    main: Main.hs
    source-dirs:         
      - test
    dependencies:
      - alpha
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-missing-pattern-synonym-signatures

